/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class VectorIndex {
  constructor(dim: number)
  get size(): number
  get dim(): number
  addBatch(vectors: Float32Array): number
  /** Find the K most similar vectors. */
  search(query: Float32Array, k: number): Array<Hit>
  save(path: string): number
  static load(path: string): VectorIndex
  /** The work runs on another thread */
  searchAsync(query: Float32Array, k: number): Promise<Array<Hit>>
}

export interface Hit {
  index: number
  score: number
}
